# Generated by Django 3.2 on 2024-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='в формате +7(900)000-00-00', max_length=25, verbose_name='Номер телефона')),
                ('e_mail', models.CharField(max_length=200, verbose_name='Адрес электронной почты')),
                ('vk', models.CharField(help_text='ссылка на сообщество в ВК', max_length=200, verbose_name='ВКонтакте')),
                ('whatsapp', models.CharField(help_text='Ссылка на вацап (формируется на специальных сервисах)', max_length=200, verbose_name='Вацап')),
                ('telegramm', models.CharField(help_text='Ссылка на телеграмм канал', max_length=200, verbose_name='Телеграмм')),
                ('address', models.CharField(help_text='!Внимание! адрес изменится только в подвале сайта', max_length=200, verbose_name='Фактический адрес')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Адрес и контакты организации',
            },
        ),
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Влияет на поисковую выдачу, Уникальное имя должно быть. Не больше 50 символов', max_length=50, verbose_name='Имя страницы')),
                ('description', models.CharField(help_text='Не больше 200 символов. Важный элемент поисковой индексации. Должен быть связный текст, по нему поисковые роботы индексируют сайт', max_length=200, verbose_name='Описание старницы.')),
                ('keywords', models.CharField(help_text='Указываетя через запятую. Не больше 250 символов. Устаревший элемент, не влияет на поисковую выдачу. Но учавствует в формировании семантического ядра', max_length=250, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'Информация для поисковых систем',
            },
        ),
    ]
