# Generated by Django 3.2 on 2024-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Влияет на поисковую выдачу, Уникальное имя должно быть. Не больше 50 символов', max_length=150, verbose_name='Название')),
                ('description', models.CharField(help_text='Не больше 200 символов. Важный элемент поисковой индексации. Должен быть связный текст, по нему поисковые роботы индексируют сайт', max_length=200, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости первой страницы',
            },
        ),
    ]
