# Generated by Django 3.2 on 2024-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_firstpagenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='seomodel',
            name='canonical_url',
            field=models.CharField(default=1, max_length=200, verbose_name='Канонический url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seomodel',
            name='google_console',
            field=models.TextField(default='', help_text='Инструкция по подключению https://support.google.com/webmasters/answer/9008080?sjid=5167314692249351332-AP#meta_tag_verification', null=True, verbose_name='Search Console Google'),
        ),
        migrations.AddField(
            model_name='seomodel',
            name='metrika',
            field=models.TextField(default='', help_text=' (Скрипт) Инструкция по получению счетчика https://yandex.ru/support/metrica/general/creating-counter.html', null=True, verbose_name='Счетчик яндекс Метрики'),
        ),
        migrations.AddField(
            model_name='seomodel',
            name='webmaster_yandex',
            field=models.TextField(default='', help_text='(Meta-тег) https://yandex.ru/support/webmaster/service/quick-start.html', null=True, verbose_name='Вебмастер Яндекс'),
        ),
    ]
