# Generated by Django 3.2 on 2024-09-19 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не больше 100 символов', max_length=100, verbose_name='Заголовок')),
                ('publish', models.BooleanField(default=False, help_text='Отметка публикации на сайте', verbose_name='Опубликовано')),
                ('text', models.TextField(help_text='Полный текст. Для разбивки на параграфы используется одинарный перенос', verbose_name='Текст')),
                ('img', models.ImageField(help_text='Красивое фото', upload_to='blog/', verbose_name='Обложка блога')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'Записи блока "О нас"',
            },
        ),
        migrations.CreateModel(
            name='ThemeBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='Тематика блога', max_length=200, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы статей и бологов',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не больше 100 символов', max_length=100, verbose_name='Заголовок статьи')),
                ('subtitle', models.CharField(help_text='Не больше 70 символов, обязательно к заполнению, используется для поисковой индексации', max_length=170, null=True, verbose_name='Подзаголовок статьи')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, help_text='Дата публикации', verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=False, help_text='Отметка публикации на сайте', verbose_name='Опубликовано')),
                ('text', models.TextField(help_text='Полный текст статьи. Для разбивки на параграфы используется одинарный перенос', verbose_name='Текст статьи')),
                ('img', models.ImageField(help_text='Красивое фото', upload_to='blog/', verbose_name='Обложка блога')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('theme', models.ForeignKey(help_text='Выберите одну тему', on_delete=django.db.models.deletion.CASCADE, to='content.themeblogmodel', verbose_name='Тема статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-pub_date'],
            },
        ),
    ]
