# Generated by Django 3.2 on 2024-09-20 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheludeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не больше 100 символов', max_length=100, verbose_name='Имя')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, help_text='Дата публикации', null=True, verbose_name='Дата публикации')),
                ('publish', models.BooleanField(default=False, help_text='Отметка публикации на сайте', verbose_name='Опубликовано')),
                ('text', models.TextField(help_text='Полный текст статьи. Для разбивки на параграфы используется одинарный перенос', verbose_name='Текста')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы игроков',
                'ordering': ['-pub_date'],
            },
        ),
    ]
