# Generated by Django 3.2 on 2024-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(help_text='в формате ЧЧ:ММ', verbose_name='Начало')),
                ('end_time', models.TimeField(help_text='в формате ЧЧ:ММ', verbose_name='Конец')),
                ('age', models.CharField(max_length=30, verbose_name='Возрастая группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
