# Generated by Django 3.2 on 2024-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не больше 100 символов', max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Не больше 70 символов, обязательно к заполнению, используется для поисковой индексации', max_length=170, null=True, verbose_name='номер телефона')),
                ('email', models.EmailField(help_text='Не больше 70 символов, обязательно к заполнению, используется для поисковой индексации', max_length=254, null=True, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Клиенты с сайта',
                'verbose_name_plural': 'Клиенты с сайта',
            },
        ),
    ]
