# Generated by Django 3.2 on 2024-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelude', '0002_clientmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='email',
        ),
    ]
